from .demand import DEMAND_FILES, DEMAND_STEPS
from .parameters import PARAMETERS_FILES, PARAMETERS_STEPS
from .run import RUN_FILES, RUN_STEPS
from .supply import SUPPLY_FILES, SUPPLY_STEPS

FILES = DEMAND_FILES + PARAMETERS_FILES + SUPPLY_FILES + RUN_FILES

STEPS = DEMAND_STEPS + PARAMETERS_STEPS + SUPPLY_STEPS + RUN_STEPS
