# Directory where all the input / output files are stored.
main_directory = "circular-city-robin/"

# Random seed to make all random steps deterministic.
random_seed = 13081996

# Generate a fictive network of radials and rings.
[circular_network]
# Number of directions for the radial roads.
nb_radials = 4
# Number of rings.
nb_rings = 2
# Radius of the rings.
# Either a scalar representing the fixed distance (in meters) between each ring.
# Or a list of the distance of each ring to the center (in meters).
radius = [400, 600]
# If true, create entry / exit ramps from the radial roads to the ring roads.
with_ramps = true
# Length of the entry ramps to the ring roads, in meters.
entry_ramps_length = 50
# Length of the exit ramps from the ring roads, in meters.
exit_ramps_length = 40
# Length of the road segments between the clockwise and counter-clockwise
# ramps, on the radial roads, in meters.
radial_inter_ramp_length = 65
# Length of the road segments between the exit and entry ramps, on the
# ring roads, in meters.
ring_inter_ramp_length = 75

[road_network_postprocess]
[road_network_postprocess.default_speed_limit]
# Speed limit (in km/h) of each edge type.
# "Radial i" are the radial roads from ring i-1 to ring i.
# "Ring i" are the roads of ring i.
# "EntryRamp i" are the entry ramps into ring i roads.
# "ExitRamp i" are the exit ramps out of ring i roads.
# "RadialTunnel i" are the radial roads connecting the ramps around ring i.
# "RingBridge i" are the ring roads connecting the ramps at ring i.
"Radial 1" = 30
"Radial 2" = 30
"Ring 1" = 40
"Ring 2" = 50
"EntryRamp 1" = 30
"EntryRamp 2" = 30
"ExitRamp 1" = 30
"ExitRamp 2" = 30
"RadialTunnel 1" = 30
"RadialTunnel 2" = 30
"RingBridge 1" = 40
"RingBridge 2" = 50

[road_network_postprocess.default_nb_lanes]
# Number of lanes of each edge type.
"Radial 1" = 2
"Radial 2" = 2
"Ring 1" = 2
"Ring 2" = 3
"EntryRamp 1" = 1
"EntryRamp 2" = 1
"ExitRamp 1" = 1
"ExitRamp 2" = 1
"RadialTunnel 1" = 2
"RadialTunnel 2" = 2
"RingBridge 1" = 2
"RingBridge 2" = 3

[road_network]
[road_network.capacities]
# Capacity (in PCE/h) of each edge type.
# Capacity is constant or time-dependent.
# For time-dependent capacities, a table of `times` and `values` must be given.
# The capacity is equal to value i between time i and i+1.
"Radial 1" = 600
"Radial 2" = 900
"Ring 1" = 1200
"Ring 2" = 2000
"EntryRamp 1" = 900
"EntryRamp 2" = { times = [06:00:00, 07:30:00, 08:30:00], values = [1600, 1000, 1600] }
"ExitRamp 1" = 900
"ExitRamp 2" = 900
"RadialTunnel 1" = 600
"RadialTunnel 2" = 900
"RingBridge 1" = 1200
"RingBridge 2" = 2000

[gravity_od_matrix]
# Generate trips from a gravity model with flows decreasing exponentially with free-flow travel time.
# Rate of decay of flows with free-flow travel time (in minutes).
exponential_decay = 0.07
# Number of trips originating from each node.
trips_per_node = 2000
# Regular expression pattern to select eligible nodes.
# The pattern "[^rl]$" matches all nodes that do not end with "r" or "l".
nodes_regex = "[^rl]$"

[simulation_parameters]
# Period to be simulated.
period = [06:00:00, 12:00:00]
# Time interval, in seconds, between two breakpoints in the travel-time functions.
recording_interval = 300
# Smoothing factor of the exponential learning model.
# Smaller values lead to slower but steadier convergence.
learning_factor = 0.01
# Number of iterations to run.
nb_iterations = 100
# Whether spillback is enabled.
spillback = true
# Maximum time, in seconds, that a vehicle can stay pending to enter a blocked edge
# (only relevant when spillback is enabled).
max_pending_duration = 30

[modes]
[modes.car_driver]
# Value of time (in €/h) when traveling as a car driver.
alpha = 10.0

[modes.public_transit]
# Speed (in km/h) of public-transit vehicles on the road network.
road_network_speed = 40
# Fixed penalty for traveling by public transit (€).
constant = 10.0
# Value of time (in €/h) when traveling in public transit..
alpha = 15.0

[mode_choice]
# Modes to be simulated.
modes = ["car_driver", "public_transit"]
# Type of choice model for mode choice (Logit or Deterministic).
model = "Logit"
# Logit scale parameter (€).
mu = 5.0

[vehicle_types]
[vehicle_types.car]
# Headway (from face to face) between two cars, in meters (only relevant when spillback is enabled).
headway = 8.0

[departure_time_choice]
# Type of choice model for departure-time choice (only ContinuousLogit for now).
model = "ContinuousLogit"
# Logit scale parameter.
mu = 2.0

[departure_time.linear_schedule]
# Penalty for early arrival (€/h).
beta = 6.0
# Penalty for late arrival (€/h).
gamma = 25.0
# Width of on-time arrival window, in seconds.
delta = 600
# Distribution for desired arrival times (Uniform or Normal).
tstar_distr = "Uniform"
# Mean desired arrival time.
tstar = 08:00:00
# Standard deviation of desired arrival times distribution, in seconds.
# For a Uniform distribution, this is half the distribution width instead.
tstar_std = 2078

[metropolis_core]
# Path to the Metropolis executable.
exec_path = "execs/metropolis_cli"
