from .econometrics import ECONOMETRICS_FILES, ECONOMETRICS_STEPS
from .road import ROAD_FILES, ROAD_STEPS
from .survey import SURVEY_FILES, SURVEY_STEPS

FILES = ROAD_FILES + SURVEY_FILES + ECONOMETRICS_FILES
STEPS = ROAD_STEPS + SURVEY_STEPS + ECONOMETRICS_STEPS
