"""Pure, side-effect-free construction of a Step dependency graph for one Config.

Split out of `pipeline.py` so that `reuse.py` can build the same kind of graph for an ancestor
config (to decide whether a Step's output can be reused from there) without triggering any of
`MetroPipeline`'s interactive prompts or cache writes.
"""

from __future__ import annotations

from collections import defaultdict
from dataclasses import dataclass
from typing import TYPE_CHECKING

from loguru import logger

if TYPE_CHECKING:
    from .config import Config
    from .file import MetroFile
    from .steps import Step


def file_key(f: MetroFile) -> str:
    """Sort key giving a stable, run-independent order for MetroFiles.

    `MetroFile.__hash__` is based on the class and the resolved path, so iterating a `set` of them
    yields an order that depends on `PYTHONHASHSEED`; sorting on the (unique) resolved path instead
    makes the order reproducible across runs.
    """
    return str(f.get_path())


@dataclass
class StepGraph:
    """The feasible Steps of one Config (after dropping those whose required inputs are never
    generated, and resolving output-file conflicts by priority), each with its required/optional
    input files and output files, plus which Step generates each file (a single one, post
    conflict-resolution).
    """

    steps: dict[Step, dict[str, set[MetroFile]]]
    generated_files: dict[MetroFile, set[Step]]


def instantiate_step_graph(
    config: Config, step_classes: list[type[Step]]
) -> tuple[dict[Step, dict[str, set[MetroFile]]], set[MetroFile]]:
    """Instantiates every Step of `step_classes` against `config`, keeping those that are
    `is_defined()` and declare outputs.

    Returns the raw (not yet feasibility/conflict-filtered) steps dict, plus every declared output
    file (including infeasible steps'), used by `MetroPipeline` for stray-file detection.
    """
    steps: dict[Step, dict[str, set[MetroFile]]] = defaultdict(dict)
    all_output_files: set[MetroFile] = set()
    for step_class in step_classes:
        for step in config.instantiate_step(step_class):
            all_output_files.update(step.output.values())
            if step.is_defined() and step.output:
                steps[step]["required_inputs"] = set(step._iter_resolved_input_files(required=True))
                steps[step]["optional_inputs"] = set(
                    step._iter_resolved_input_files(required=False)
                )
                steps[step]["outputs"] = set(step.output.values())
    return dict(steps), all_output_files


def compute_feasible(
    steps: dict[Step, dict[str, set[MetroFile]]],
) -> tuple[dict[MetroFile, set[Step]], set[MetroFile]]:
    """Computes, from `steps`, the generated files of the feasible steps (those whose required
    inputs are all generated by some other feasible step), dropping the rest from `steps` in place.

    Returns `(generated_files, primary_input_files)` for the resulting feasible steps.
    """
    generated_files: dict[MetroFile, set[Step]] = defaultdict(set)
    primary_input_files: set[MetroFile] = set()
    remaining = set(steps.keys())
    while True:
        # `remaining` and the output file sets below are iterated in sorted order so that the
        # insertion order of `generated_files` (which drives `find_next_conflict`) does not depend
        # on object ids / hash randomization.
        steps_to_add = [
            s
            for s in sorted(remaining, key=str)
            if steps[s]["required_inputs"].issubset(generated_files)
        ]
        if not steps_to_add:
            break
        remaining -= set(steps_to_add)
        for s in steps_to_add:
            if s.is_primary():
                for f in steps[s]["required_inputs"] | steps[s]["optional_inputs"]:
                    primary_input_files.add(f)
            for f in sorted(steps[s]["outputs"], key=file_key):
                generated_files[f].add(s)
    for s in remaining:
        steps.pop(s)
    return generated_files, primary_input_files


def find_next_conflict(generated_files: dict[MetroFile, set[Step]]) -> set[Step] | None:
    for ofile, steps in generated_files.items():
        if len(steps) >= 2:
            steps_str = ", ".join(sorted(map(str, steps)))
            logger.debug(f"Multiple steps are generating file {ofile}: {steps_str}")
            return steps
    return None


def least_priority_steps(conflict: set[Step]) -> set[Step]:
    """Returns the Steps with the least priority from a set of Steps.

    An ordering needs to be defined for the Step type (functions __lt__ and __eq__).
    """
    assert len(conflict) > 1
    ordered_steps = list(sorted(conflict))
    return set(ordered_steps[:-1])


def resolve_feasible_graph(
    steps: dict[Step, dict[str, set[MetroFile]]],
) -> tuple[dict[MetroFile, set[Step]], set[MetroFile]]:
    """Repeatedly computes feasibility and resolves output-file conflicts by priority, mutating
    `steps` in place, until no two steps generate the same file.
    """
    while True:
        generated_files, primary_input_files = compute_feasible(steps)
        conflict = find_next_conflict(generated_files)
        if conflict is None:
            return generated_files, primary_input_files
        for s in sorted(least_priority_steps(conflict), key=str):
            steps.pop(s)


def build_step_graph(config: Config, step_classes: list[type[Step]]) -> StepGraph:
    """Builds the full feasible step graph for `config`.

    Unlike `MetroPipeline`, this never prompts the user or writes any cache: it is safe to call
    on an ancestor config purely to inspect it (see `reuse.py`).
    """
    steps, _all_output_files = instantiate_step_graph(config, step_classes)
    generated_files, _primary_input_files = resolve_feasible_graph(steps)
    return StepGraph(steps=steps, generated_files=generated_files)


def topological_order(
    steps: dict[Step, dict[str, set[MetroFile]]], generated_files: dict[MetroFile, set[Step]]
) -> list[Step]:
    """Returns the Steps of `steps` (assumed already feasible) ordered so that every Step comes
    after every Step producing one of its (required, or optional-and-actually-generated) input
    files.
    """
    order: list[Step] = []
    available_files: set[MetroFile] = set()
    remaining = set(steps.keys())
    while remaining:
        ready = [
            s
            for s in sorted(remaining, key=str)
            if steps[s]["required_inputs"].issubset(available_files)
            and steps[s]["optional_inputs"].intersection(generated_files).issubset(available_files)
        ]
        assert ready, "Cyclic or infeasible step graph"
        for s in ready:
            order.append(s)
            available_files.update(steps[s]["outputs"])
        remaining -= set(ready)
    return order
