from .pedestrian_network import PEDESTRIAN_NETWORK_FILES, PEDESTRIAN_NETWORK_STEPS
from .road_network import ROAD_NETWORK_FILES, ROAD_NETWORK_STEPS

FILES = ROAD_NETWORK_FILES + PEDESTRIAN_NETWORK_FILES

STEPS = ROAD_NETWORK_STEPS + PEDESTRIAN_NETWORK_STEPS
