from .bicycle_network import BICYCLE_NETWORK_FILES, BICYCLE_NETWORK_STEPS
from .pedestrian_network import PEDESTRIAN_NETWORK_FILES, PEDESTRIAN_NETWORK_STEPS
from .public_transit import PUBLIC_TRANSIT_FILES, PUBLIC_TRANSIT_STEPS
from .road_network import ROAD_NETWORK_FILES, ROAD_NETWORK_STEPS

FILES = ROAD_NETWORK_FILES + PEDESTRIAN_NETWORK_FILES + BICYCLE_NETWORK_FILES + PUBLIC_TRANSIT_FILES

STEPS = ROAD_NETWORK_STEPS + PEDESTRIAN_NETWORK_STEPS + BICYCLE_NETWORK_STEPS + PUBLIC_TRANSIT_STEPS
