from .departure_time import DEPARTURE_TIME_FILES, DEPARTURE_TIME_STEPS
from .modes import MODES_FILES, MODES_STEPS
from .od_matrix import OD_MATRIX_FILES, OD_MATRIX_STEPS
from .population import POPULATION_STEPS
from .zones import ZONES_FILES, ZONES_STEPS

FILES = ZONES_FILES + OD_MATRIX_FILES + DEPARTURE_TIME_FILES + MODES_FILES

STEPS = ZONES_STEPS + OD_MATRIX_STEPS + DEPARTURE_TIME_STEPS + MODES_STEPS + POPULATION_STEPS
