main_directory = "output-joint_tours/"

random_seed = 13081996

[survey]
[survey.mobisurvstd]
path = "data/surveys/"
bulk = true

[joint_travel]
features = [
    "nb_activities",
    "total_activity_duration",
    "total_distance",
    "first_activity_start",
    "last_activity_end",
    "age",
    "nb_persons",
    "nb_minors",
    "nb_cars",
    "nb_driving_licenses",
    "minor_ratio",
    "car_ratio",
    "driving_license_ratio",
    "woman",
    "has_driving_license",
    "has_leisure_purpose",
    "has_shopping_purpose",
    "has_task_purpose",
    "has_other_purpose",
    "has_work_purpose",
    "has_education_purpose",
    "has_escort_purpose",
    "professional_activity",
]
