main_directory = "output/"

custom_steps = ["custom_steps.py"]

random_seed = 123454321

[bottleneck_network]
free_flow_travel_time = 30
capacity = 16_000

[node_od_matrix]
each = 10_000

[uniform_draws]
systematic_sampling = true

[mode_choice]
modes = ["car_driver"]

[modes]
[modes.car_driver]
alpha = 10

[departure_time_choice]
model = "ContinuousLogit"
mu = 1

[departure_time.linear_schedule]
beta = 5
gamma = 7
tstar = 07:30:00

[simulation]
period = [07:00:00, 08:00:00]
recording_interval = 60
learning_factor = 0.1
nb_iterations = 200
