from __future__ import annotations

from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from loguru import logger

from pymetropolis.metro_common import MetropyError
from pymetropolis.metro_pipeline.parameters import (
    BoolParameter,
    CustomParameter,
    FloatParameter,
    IntParameter,
)
from pymetropolis.metro_pipeline.steps import Step

if TYPE_CHECKING:
    from collections.abc import Callable, Collection, Iterable

    import polars as pl


class MetroMetaType(type):
    _repr: str
    _name: str

    def __repr__(cls):
        return cls._repr

    def __str__(cls):
        return cls._name


class MetaVehicle(MetroMetaType):
    """Meta class to define road vehicles."""

    def is_car(cls) -> bool:
        return False

    def has_passenger(cls) -> bool:
        """Returns true if the vehicle has passengers in it."""
        return False

    def can_take_hov_edges(cls) -> bool:
        """Returns true if the vehicle can travel on HOV lanes."""
        return cls.has_passenger()

    def get_congestion_share(cls, nb_passengers: float) -> float:
        """Share of generated congestion that should be attributed to the vehicle compared to the
        base vehicle.
        """
        return 1.0


class CarVehicle(MetaVehicle):
    def is_car(cls) -> bool:
        return True


class CarDriverAloneVehicle(metaclass=CarVehicle):
    _repr = "car_driver_alone"
    _name = "car driver alone"


class CarDriverMultiVehicle(metaclass=CarVehicle):
    _repr = "car_driver_multi"
    _name = "car driver multi"

    @classmethod
    def has_passenger(cls) -> bool:
        return True


class CarPassengerVehicle(metaclass=CarVehicle):
    _repr = "car_passenger"
    _name = "car passenger"

    @classmethod
    def get_congestion_share(cls, nb_passengers: float) -> float:
        # Congestion is generated by the "driver" vehicle. No congestion is generated by the
        # passenger vehicles to prevent double counts.
        return 0.0

    @classmethod
    def has_passenger(cls) -> bool:
        return True


class CarRidesharingVehicle(metaclass=CarVehicle):
    _repr = "car_ridesharing"
    _name = "car ridesharing"

    @classmethod
    def get_congestion_share(cls, nb_passengers: float) -> float:
        # Congestion generation is split among all persons in the vehicle.
        return 1 / (1 + nb_passengers)

    @classmethod
    def has_passenger(cls) -> bool:
        return True


class MetaMode(MetroMetaType):
    """Meta class to define modes."""

    @classmethod
    def is_trip_based(cls) -> bool:
        """Returns true if the mode is trip-based, i.e., it involves traveling."""
        return True

    @classmethod
    def is_road_based(cls) -> bool:
        """Returns true if the mode involves trips on the road network."""
        return False

    @classmethod
    def is_car_based(cls) -> bool:
        """Returns true if the mode is car based."""
        return False

    @classmethod
    def is_pedestrian_based(cls) -> bool:
        """Returns true if the mode involves trips on the pedestrian network."""
        return False


class RoadMode(MetaMode):
    """Meta class for road-based modes."""

    @classmethod
    def is_road_based(cls) -> bool:
        return True

    @classmethod
    def vehicle(cls) -> MetaVehicle:
        raise NotImplementedError


class CarMode(RoadMode):
    """Meta class for car-based modes."""

    @classmethod
    def is_car_based(cls) -> bool:
        return True

    @classmethod
    def is_driver(cls) -> bool:
        """Whether the person taking this mode is known to be the driver of the car."""
        return False

    @classmethod
    def get_fuel_share(cls, nb_passengers: float) -> float:
        """Share of total fuel cost that should be attributed to the agent."""
        return 1.0


class CarDriver(metaclass=CarMode):
    _name = "car driver"
    _repr = "car_driver"

    @classmethod
    def is_driver(cls) -> bool:
        return True

    @classmethod
    def vehicle(cls) -> MetaVehicle:
        return CarDriverAloneVehicle


class CarDriverWithPassengers(metaclass=CarMode):
    _name = "car driver with passengers"
    _repr = "car_driver_with_passengers"

    @classmethod
    def is_driver(cls) -> bool:
        return True

    @classmethod
    def vehicle(cls) -> MetaVehicle:
        return CarDriverMultiVehicle


class CarPassenger(metaclass=CarMode):
    _name = "car passenger"
    _repr = "car_passenger"

    @classmethod
    def get_fuel_share(cls, nb_passengers: float) -> float:
        # Car drivers are assumed to pay the fuel cost price.
        # TODO. This could be configurable.
        return 0.0

    @classmethod
    def vehicle(cls) -> MetaVehicle:
        return CarPassengerVehicle


class CarRidesharing(metaclass=CarMode):
    _name = "car ridesharing"
    _repr = "car_ridesharing"

    # Note. The agent can be either the driver or a passenger so `is_driver` is false.

    @classmethod
    def get_fuel_share(cls, nb_passengers: float) -> float:
        # The driver is unknown. The fuel is assumed to be split among all persons in the car
        # (1 + nb_passengers).
        return 1 / (1 + nb_passengers)

    @classmethod
    def vehicle(cls) -> MetaVehicle:
        return CarRidesharingVehicle


class PublicTransit(metaclass=MetaMode):
    _name = "public transit"
    _repr = "public_transit"


class Walking(metaclass=MetaMode):
    _name = "walking"
    _repr = "walking"

    @classmethod
    def is_pedestrian_based(cls) -> bool:
        return True


class Bicycle(metaclass=MetaMode):
    _name = "bicycle"
    _repr = "bicycle"

    @classmethod
    def is_pedestrian_based(cls) -> bool:
        return True


class OutsideOption(metaclass=MetaMode):
    _name = "outside option"
    _repr = "outside_option"

    @classmethod
    def is_trip_based(cls) -> bool:
        return False


CAR_MODES: list[CarMode] = [CarDriver, CarDriverWithPassengers, CarPassenger, CarRidesharing]

METRO_MODES: list[MetaMode] = [*CAR_MODES, PublicTransit, Walking, Bicycle, OutsideOption]

METRO_VEHICLES: list[MetaVehicle] = [
    CarDriverAloneVehicle,
    CarDriverMultiVehicle,
    CarPassengerVehicle,
    CarRidesharingVehicle,
]


def mode_from_str(s: str) -> MetaMode:
    for mode in METRO_MODES:
        if repr(mode) == s:
            return mode
    raise MetropyError(f"Unsupported mode: `{s}`")


def validate_mode(value: Any) -> MetaMode:
    if not isinstance(value, str):
        raise MetropyError(f"Mode entries must be strings, got `{value}`")
    return mode_from_str(value)


def modes_validator(value: Any) -> list[MetaMode]:
    if not isinstance(value, list):
        raise MetropyError(f"Invalid modes parameter: list of modes expected, got `{value}`")
    if len(value) == 0:
        raise MetropyError("Invalid modes parameter: at least one mode must be defined")
    modes = [validate_mode(v) for v in value]
    unique_modes = set(modes)
    if len(modes) != len(unique_modes):
        raise MetropyError(f"Invalid modes parameter: duplicated modes found, got `{value}`")
    return modes


class StepWithModes(Step):
    """A Step subclass for Steps that depend on the list of simulated modes.

    The class is defined here, and not in `metro_simulation`, because it is used by Steps of the
    demand, the simulation and the calibration packages.
    """

    modes = CustomParameter(
        "mode_choice.modes",
        validator=modes_validator,
        validator_description="list of strings representing existing modes",
        description="List of modes the agents can used to travel.",
        example='`["car_driver", "public_transit"]`',
    )

    def _iter_modes(self) -> Iterable[MetaMode]:
        yield from self.modes or []

    def _check_any(self, condition: Callable[[MetaMode], bool]) -> bool:
        """Returns true if the condition is valid for any mode."""
        return any(condition(m) for m in self._iter_modes())

    def has_any_mode(self) -> bool:
        """Returns `True` if the configuration has at least one mode defined."""
        assert self.modes is None or len(self.modes) >= 1
        return self.modes is not None

    def has_mode_choice(self) -> bool:
        """Returns `True` if the configuration implies a mode choice (i.e., there are at least two
        modes).
        """
        return self.modes is not None and len(self.modes) >= 2

    def has_mode(self, mode: str) -> bool:
        """Returns `True` if the configuration has a given mode defined."""
        return self.has_mode_class(mode_from_str(mode))

    def has_mode_class(self, mode: MetaMode) -> bool:
        """Returns `True` if the configuration has a given mode defined."""
        return self.modes is not None and mode in self.modes

    def has_trip_mode(self) -> bool:
        """Returns `True` if the configuration has at least one trip-based mode (i.e., different
        from "outside_option").
        """
        return self._check_any(lambda m: m.is_trip_based())

    def has_car_mode(self) -> bool:
        """Returns `True` if the configuration has at least one car-based mode."""
        return self._check_any(lambda m: m.is_car_based())

    def has_road_mode(self) -> bool:
        """Returns `True` if the configuration has at least one road-based mode."""
        return self._check_any(lambda m: m.is_road_based())

    def has_pedestrian_mode(self) -> bool:
        """Returns `True` if the configuration has at least one pedestrian mode (e.g., walking,
        bicycle).
        """
        return self._check_any(lambda m: m.is_pedestrian_based())


@dataclass(frozen=True)
class ModeAvailabilityRules:
    """Rules defining which modes are available to a tour.

    The same rules must be used when estimating the mode-choice model and when simulating, so that
    the choice sets are consistent.
    """

    car_driver_requires_car: bool = True
    car_driver_requires_driving_license: bool = True
    car_driver_min_age: int | None = None
    car_passenger_requires_car: bool = True
    car_ridesharing_requires_car: bool = True
    no_solo_modes_for_joint_tours: bool = True
    bicycle_requires_bicycle: bool = False
    walking_max_distance: float | None = None
    bicycle_max_distance: float | None = None


# Column used by each availability rule. They are shared by `SurveyedToursFile` and the trips
# generated in the simulation.
CAR_OWNERSHIP_COLUMN = "nb_cars"
DRIVING_LICENSE_COLUMN = "has_driving_license"
AGE_COLUMN = "age"
JOINT_TOUR_COLUMN = "joint_tour"
BICYCLE_OWNERSHIP_COLUMN = "nb_bicycles"
TOUR_DISTANCE_COLUMN = "total_distance"

AVAILABILITY_COLUMNS = (
    CAR_OWNERSHIP_COLUMN,
    DRIVING_LICENSE_COLUMN,
    AGE_COLUMN,
    JOINT_TOUR_COLUMN,
    BICYCLE_OWNERSHIP_COLUMN,
    TOUR_DISTANCE_COLUMN,
)


@dataclass(frozen=True)
class _AvailabilityRule:
    column: str
    # Human-readable description of the restriction, used in warnings.
    description: str
    # Function returning a boolean expression (true if the mode is available) from the column.
    condition: Callable[[pl.Expr], pl.Expr]


def _mode_rules(mode: MetaMode, rules: ModeAvailabilityRules) -> list[_AvailabilityRule]:
    """Returns the active availability rules for a given mode."""
    out = []
    if isinstance(mode, CarMode):
        if mode.is_driver():
            requires_car = rules.car_driver_requires_car
        elif mode is CarPassenger:
            requires_car = rules.car_passenger_requires_car
        elif mode is CarRidesharing:
            requires_car = rules.car_ridesharing_requires_car
        else:
            requires_car = True
        if requires_car:
            out.append(
                _AvailabilityRule(
                    CAR_OWNERSHIP_COLUMN, "car owners", lambda c: c.ge(1).fill_null(False)
                )
            )
        if mode.is_driver() and rules.car_driver_requires_driving_license:
            out.append(
                _AvailabilityRule(
                    DRIVING_LICENSE_COLUMN, "driving-license holders", lambda c: c.fill_null(False)
                )
            )
        if mode.is_driver() and rules.car_driver_min_age is not None:
            min_age = rules.car_driver_min_age
            out.append(
                _AvailabilityRule(
                    AGE_COLUMN,
                    f"persons aged {min_age} or more",
                    lambda c: c.ge(min_age).fill_null(False),
                )
            )
        if rules.no_solo_modes_for_joint_tours and not mode.vehicle().has_passenger():
            out.append(
                _AvailabilityRule(
                    JOINT_TOUR_COLUMN, "non-joint tours", lambda c: c.not_().fill_null(True)
                )
            )
    if mode is Bicycle and rules.bicycle_requires_bicycle:
        out.append(
            _AvailabilityRule(
                BICYCLE_OWNERSHIP_COLUMN, "bicycle owners", lambda c: c.ge(1).fill_null(False)
            )
        )
    max_distance = {Walking: rules.walking_max_distance, Bicycle: rules.bicycle_max_distance}.get(
        mode
    )
    if max_distance is not None:
        out.append(
            _AvailabilityRule(
                TOUR_DISTANCE_COLUMN,
                f"tours shorter than {max_distance:,} meters",
                lambda c: c.le(max_distance).fill_null(True),
            )
        )
    return out


def mode_availability_conditions(
    mode: MetaMode, rules: ModeAvailabilityRules, columns: Collection[str]
) -> list[pl.Expr]:
    """Returns the boolean expressions that must all be true for `mode` to be available.

    The expressions are evaluated on a DataFrame with the columns `nb_cars`,
    `has_driving_license`, `age`, `joint_tour`, `nb_bicycles` and `total_distance`. A rule whose
    column is not in `columns` is skipped (see `warn_missing_availability_columns`).
    """
    import polars as pl

    return [
        rule.condition(pl.col(rule.column))
        for rule in _mode_rules(mode, rules)
        if rule.column in columns
    ]


def mode_availability_expr(
    mode: MetaMode, rules: ModeAvailabilityRules, columns: Collection[str]
) -> pl.Expr:
    """Returns a boolean expression which is true if `mode` is available."""
    import polars as pl

    conditions = mode_availability_conditions(mode, rules, columns)
    return pl.all_horizontal(*conditions) if conditions else pl.lit(True)


def warn_missing_availability_columns(
    modes: Iterable[MetaMode],
    rules: ModeAvailabilityRules,
    columns: Collection[str],
    level: str = "WARNING",
) -> None:
    """Logs a message (with the given level) for each active availability rule which cannot be
    applied because its column is missing.
    """
    for mode in modes:
        for rule in _mode_rules(mode, rules):
            if rule.column not in columns:
                logger.log(
                    level,
                    f"`{rule.column}` is not available: mode `{mode!r}` will not be restricted to "
                    f"{rule.description}.",
                )


class StepWithModeAvailability(Step):
    """A Step subclass for Steps that depend on the rules defining which modes are available.

    These rules are used both when estimating the mode-choice model and when generating the
    alternatives of the simulation, so that the choice sets are consistent.
    """

    car_driver_requires_car = BoolParameter(
        "mode_availability.car_driver.requires_car",
        default=True,
        description=(
            "If `true`, the car-driver modes are only available to persons whose household owns at "
            "least one car."
        ),
    )
    car_driver_requires_driving_license = BoolParameter(
        "mode_availability.car_driver.requires_driving_license",
        default=True,
        description=(
            "If `true`, the car-driver modes are only available to persons with a driving license."
        ),
    )
    car_driver_min_age = IntParameter(
        "mode_availability.car_driver.min_age",
        lower_bound=0,
        description="Minimum age required for the car-driver modes.",
        note="If not specified, there is no age restriction.",
        example="`18`",
    )
    car_passenger_requires_car = BoolParameter(
        "mode_availability.car_passenger.requires_car",
        default=True,
        description=(
            "If `true`, the car-passenger modes are only available to persons whose household owns "
            "at least one car."
        ),
        note=(
            'This does not apply to the "car_ridesharing" mode, use '
            "`mode_availability.car_ridesharing.requires_car` instead."
        ),
    )
    car_ridesharing_requires_car = BoolParameter(
        "mode_availability.car_ridesharing.requires_car",
        default=True,
        description=(
            'If `true`, the "car_ridesharing" mode is only available to persons whose household '
            "owns at least one car."
        ),
    )
    no_solo_modes_for_joint_tours = BoolParameter(
        "mode_availability.no_solo_modes_for_joint_tours",
        default=True,
        description=(
            'If `true`, car modes without passenger (i.e., "car_driver") are not available for '
            "tours done jointly with other household members."
        ),
    )
    bicycle_requires_bicycle = BoolParameter(
        "mode_availability.bicycle.requires_bicycle",
        default=False,
        description=(
            "If `true`, the bicycle mode is only available to persons whose household owns at "
            "least one bicycle."
        ),
    )
    walking_max_distance = FloatParameter(
        "mode_availability.walking.max_distance",
        lower_bound=0.0,
        description=(
            "Maximum tour distance (sum of the Euclidean distances of the trips) for the walking "
            "mode to be available, in meters."
        ),
        note="If not specified, there is no distance restriction.",
    )
    bicycle_max_distance = FloatParameter(
        "mode_availability.bicycle.max_distance",
        lower_bound=0.0,
        description=(
            "Maximum tour distance (sum of the Euclidean distances of the trips) for the bicycle "
            "mode to be available, in meters."
        ),
        note="If not specified, there is no distance restriction.",
    )

    def availability_rules(self) -> ModeAvailabilityRules:
        """Returns the mode-availability rules defined in the config."""
        return ModeAvailabilityRules(
            car_driver_requires_car=bool(self.car_driver_requires_car),
            car_driver_requires_driving_license=bool(self.car_driver_requires_driving_license),
            car_driver_min_age=self.car_driver_min_age,
            car_passenger_requires_car=bool(self.car_passenger_requires_car),
            car_ridesharing_requires_car=bool(self.car_ridesharing_requires_car),
            no_solo_modes_for_joint_tours=bool(self.no_solo_modes_for_joint_tours),
            bicycle_requires_bicycle=bool(self.bicycle_requires_bicycle),
            walking_max_distance=self.walking_max_distance,
            bicycle_max_distance=self.bicycle_max_distance,
        )

    def has_distance_caps(self) -> bool:
        """Returns `True` if the availability of some modes depends on the tour distance."""
        return self.walking_max_distance is not None or self.bicycle_max_distance is not None
