from collections.abc import Callable, Iterable
from typing import Any

from pymetropolis.metro_common import MetropyError
from pymetropolis.metro_pipeline.parameters import CustomParameter
from pymetropolis.metro_pipeline.steps import Step


class MetroMetaType(type):
    _repr: str
    _name: str

    def __repr__(cls):
        return cls._repr

    def __str__(cls):
        return cls._name


class MetaVehicle(MetroMetaType):
    """Meta class to define road vehicles."""

    def is_car(cls) -> bool:
        return False

    def has_passenger(cls) -> bool:
        """Returns true if the vehicle has passengers in it."""
        return False

    def can_take_hov_edges(cls) -> bool:
        """Returns true if the vehicle can travel on HOV lanes."""
        return cls.has_passenger()

    def get_congestion_share(cls, nb_passengers: float) -> float:
        """Share of generated congestion that should be attributed to the vehicle compared to the
        base vehicle.
        """
        return 1.0


class CarVehicle(MetaVehicle):
    def is_car(cls) -> bool:
        return True


class CarDriverAloneVehicle(metaclass=CarVehicle):
    _repr = "car_driver_alone"
    _name = "car driver alone"


class CarDriverMultiVehicle(metaclass=CarVehicle):
    _repr = "car_driver_multi"
    _name = "car driver multi"

    @classmethod
    def has_passenger(cls) -> bool:
        return True


class CarPassengerVehicle(metaclass=CarVehicle):
    _repr = "car_passenger"
    _name = "car passenger"

    @classmethod
    def get_congestion_share(cls, nb_passengers: float) -> float:
        # Congestion is generated by the "driver" vehicle. No congestion is generated by the
        # passenger vehicles to prevent double counts.
        return 0.0

    @classmethod
    def has_passenger(cls) -> bool:
        return True


class CarRidesharingVehicle(metaclass=CarVehicle):
    _repr = "car_ridesharing"
    _name = "car ridesharing"

    @classmethod
    def get_congestion_share(cls, nb_passengers: float) -> float:
        # Congestion generation is split among all persons in the vehicle.
        return 1 / (1 + nb_passengers)

    @classmethod
    def has_passenger(cls) -> bool:
        return True


class MetaMode(MetroMetaType):
    """Meta class to define modes."""

    @classmethod
    def is_trip_based(cls) -> bool:
        """Returns true if the mode is trip-based, i.e., it involves traveling."""
        return True

    @classmethod
    def is_road_based(cls) -> bool:
        """Returns true if the mode involves trips on the road network."""
        return False

    @classmethod
    def is_car_based(cls) -> bool:
        """Returns true if the mode is car based."""
        return False

    @classmethod
    def is_pedestrian_based(cls) -> bool:
        """Returns true if the mode involves trips on the pedestrian network."""
        return False


class RoadMode(MetaMode):
    """Meta class for road-based modes."""

    @classmethod
    def is_road_based(cls) -> bool:
        return True

    @classmethod
    def vehicle(cls) -> MetaVehicle:
        raise NotImplementedError


class CarMode(RoadMode):
    """Meta class for car-based modes."""

    @classmethod
    def is_car_based(cls) -> bool:
        return True

    @classmethod
    def requires_car(cls) -> bool:
        """Whether this mode requires a car to be taken."""
        return True

    @classmethod
    def requires_driving_license(cls) -> bool:
        """Whether this mode requires a driving license to be taken."""
        return False

    @classmethod
    def get_fuel_share(cls, nb_passengers: float) -> float:
        """Share of total fuel cost that should be attributed to the agent."""
        return 1.0


class CarDriver(metaclass=CarMode):
    _name = "car driver"
    _repr = "car_driver"

    @classmethod
    def requires_driving_license(cls) -> bool:
        return True

    @classmethod
    def vehicle(cls) -> MetaVehicle:
        return CarDriverAloneVehicle


class CarDriverWithPassengers(metaclass=CarMode):
    _name = "car driver with passengers"
    _repr = "car_driver_with_passengers"

    @classmethod
    def requires_driving_license(cls) -> bool:
        return True

    @classmethod
    def vehicle(cls) -> MetaVehicle:
        return CarDriverMultiVehicle


class CarPassenger(metaclass=CarMode):
    _name = "car passenger"
    _repr = "car_passenger"

    @classmethod
    def requires_driving_license(cls) -> bool:
        return False

    @classmethod
    def get_fuel_share(cls, nb_passengers: float) -> float:
        # Car drivers are assumed to pay the fuel cost price.
        # TODO. This could be configurable.
        return 0.0

    @classmethod
    def vehicle(cls) -> MetaVehicle:
        return CarPassengerVehicle


class CarRidesharing(metaclass=CarMode):
    _name = "car ridesharing"
    _repr = "car_ridesharing"

    @classmethod
    def requires_driving_license(cls) -> bool:
        # Note. As driver, a driving license is required, but we don't know if the agent is driving.
        return False

    @classmethod
    def get_fuel_share(cls, nb_passengers: float) -> float:
        # The driver is unknown. The fuel is assumed to be split among all persons in the car
        # (1 + nb_passengers).
        return 1 / (1 + nb_passengers)

    @classmethod
    def vehicle(cls) -> MetaVehicle:
        return CarRidesharingVehicle


class PublicTransit(metaclass=MetaMode):
    _name = "public transit"
    _repr = "public_transit"


class Walking(metaclass=MetaMode):
    _name = "walking"
    _repr = "walking"

    @classmethod
    def is_pedestrian_based(cls) -> bool:
        return True


class Bicycle(metaclass=MetaMode):
    _name = "bicycle"
    _repr = "bicycle"

    @classmethod
    def is_pedestrian_based(cls) -> bool:
        return True


class OutsideOption(metaclass=MetaMode):
    _name = "outside option"
    _repr = "outside_option"

    @classmethod
    def is_trip_based(cls) -> bool:
        return False


CAR_MODES: list[CarMode] = [CarDriver, CarDriverWithPassengers, CarPassenger, CarRidesharing]

METRO_MODES: list[MetaMode] = [*CAR_MODES, PublicTransit, Walking, Bicycle, OutsideOption]

METRO_VEHICLES: list[MetaVehicle] = [
    CarDriverAloneVehicle,
    CarDriverMultiVehicle,
    CarPassengerVehicle,
    CarRidesharingVehicle,
]


def mode_from_str(s: str) -> MetaMode:
    for mode in METRO_MODES:
        if repr(mode) == s:
            return mode
    raise MetropyError(f"Unsupported mode: `{s}`")


def validate_mode(value: Any) -> MetaMode:
    if not isinstance(value, str):
        raise MetropyError(f"Mode entries must be strings, got `{value}`")
    return mode_from_str(value)


def modes_validator(value: Any) -> list[MetaMode]:
    if not isinstance(value, list):
        raise MetropyError(f"Invalid modes parameter: list of modes expected, got `{value}`")
    if len(value) == 0:
        raise MetropyError("Invalid modes parameter: at least one mode must be defined")
    modes = [validate_mode(v) for v in value]
    unique_modes = set(modes)
    if len(modes) != len(unique_modes):
        raise MetropyError(f"Invalid modes parameter: duplicated modes found, got `{value}`")
    return modes


class StepWithModes(Step):
    """A Step subclass for Steps that depend on the list of simulated modes.

    The class is defined here, and not in `metro_simulation`, because it is used by Steps of the
    demand, the simulation and the calibration packages.
    """

    modes = CustomParameter(
        "mode_choice.modes",
        validator=modes_validator,
        validator_description="list of strings representing existing modes",
        description="List of modes the agents can used to travel.",
        example='`["car_driver", "public_transit"]`',
    )

    def _iter_modes(self) -> Iterable[MetaMode]:
        yield from self.modes or []

    def _check_any(self, condition: Callable[[MetaMode], bool]) -> bool:
        """Returns true if the condition is valid for any mode."""
        return any(condition(m) for m in self._iter_modes())

    def has_any_mode(self) -> bool:
        """Returns `True` if the configuration has at least one mode defined."""
        assert self.modes is None or len(self.modes) >= 1
        return self.modes is not None

    def has_mode_choice(self) -> bool:
        """Returns `True` if the configuration implies a mode choice (i.e., there are at least two
        modes).
        """
        return self.modes is not None and len(self.modes) >= 2

    def has_mode(self, mode: str) -> bool:
        """Returns `True` if the configuration has a given mode defined."""
        return self.has_mode_class(mode_from_str(mode))

    def has_mode_class(self, mode: MetaMode) -> bool:
        """Returns `True` if the configuration has a given mode defined."""
        return self.modes is not None and mode in self.modes

    def has_trip_mode(self) -> bool:
        """Returns `True` if the configuration has at least one trip-based mode (i.e., different
        from "outside_option").
        """
        return self._check_any(lambda m: m.is_trip_based())

    def has_car_mode(self) -> bool:
        """Returns `True` if the configuration has at least one car-based mode."""
        return self._check_any(lambda m: m.is_car_based())

    def has_road_mode(self) -> bool:
        """Returns `True` if the configuration has at least one road-based mode."""
        return self._check_any(lambda m: m.is_road_based())

    def has_pedestrian_mode(self) -> bool:
        """Returns `True` if the configuration has at least one pedestrian mode (e.g., walking,
        bicycle).
        """
        return self._check_any(lambda m: m.is_pedestrian_based())
