from .files import (
    PrimaryCarTripsAccessEgressFile,
    TripsBicycleCostsFile,
    TripsBicycleNodesFile,
    TripsCarFreeFlowTravelTimesFile,
    TripsPedestrianDistancesFile,
    TripsPedestrianNodesFile,
    TripsPublicTransitItinerariesFile,
    TripsRoadNodesFile,
    ZoneODLevel1CongestedTravelTimesFile,
    ZoneODLevel1FreeFlowTravelTimesFile,
    ZoneODLevel2CongestedTravelTimesFile,
    ZoneODLevel2FreeFlowTravelTimesFile,
    ZoneODLevel3CongestedTravelTimesFile,
    ZoneODLevel3FreeFlowTravelTimesFile,
    ZoneODLevel4CongestedTravelTimesFile,
    ZoneODLevel4FreeFlowTravelTimesFile,
    ZoneODLevel5CongestedTravelTimesFile,
    ZoneODLevel5FreeFlowTravelTimesFile,
    ZonesLevel1RoadNodeFile,
    ZonesLevel2RoadNodeFile,
    ZonesLevel3RoadNodeFile,
    ZonesLevel4RoadNodeFile,
    ZonesLevel5RoadNodeFile,
)
from .od_pairs import (
    BicycleODNodesFromCoordinatesStep,
    PedestrianODNodesFromCoordinatesStep,
    RoadODNodesFromCoordinatesStep,
)
from .od_zones import (
    ZonesLevel1RoadNodesStep,
    ZonesLevel2RoadNodesStep,
    ZonesLevel3RoadNodesStep,
    ZonesLevel4RoadNodesStep,
    ZonesLevel5RoadNodesStep,
    ZonesODCongestedTravelTimesStep,
    ZonesODFreeFlowTravelTimesStep,
)
from .opentripplanner import TripsOpenTripPlannerStep
from .r5 import TripsPublicTransitTravelTimeFromR5Step
from .road_split import CarAccessEgressStep, RoadNetworkPrimaryEdgesStep
from .routing_cli import (
    TripsBicycleCostStep,
    TripsCarFreeFlowTravelTimesStep,
    TripsPedestrianDistancesStep,
)

ROUTING_FILES = [
    TripsPedestrianNodesFile,
    TripsPedestrianDistancesFile,
    TripsBicycleNodesFile,
    TripsBicycleCostsFile,
    TripsRoadNodesFile,
    TripsCarFreeFlowTravelTimesFile,
    PrimaryCarTripsAccessEgressFile,
    TripsPublicTransitItinerariesFile,
    ZoneODLevel1CongestedTravelTimesFile,
    ZoneODLevel2CongestedTravelTimesFile,
    ZoneODLevel3CongestedTravelTimesFile,
    ZoneODLevel4CongestedTravelTimesFile,
    ZoneODLevel5CongestedTravelTimesFile,
    ZoneODLevel1FreeFlowTravelTimesFile,
    ZoneODLevel2FreeFlowTravelTimesFile,
    ZoneODLevel3FreeFlowTravelTimesFile,
    ZoneODLevel4FreeFlowTravelTimesFile,
    ZoneODLevel5FreeFlowTravelTimesFile,
    ZonesLevel1RoadNodeFile,
    ZonesLevel2RoadNodeFile,
    ZonesLevel3RoadNodeFile,
    ZonesLevel4RoadNodeFile,
    ZonesLevel5RoadNodeFile,
]

ROUTING_STEPS = [
    PedestrianODNodesFromCoordinatesStep,
    BicycleODNodesFromCoordinatesStep,
    RoadODNodesFromCoordinatesStep,
    TripsPedestrianDistancesStep,
    TripsBicycleCostStep,
    TripsCarFreeFlowTravelTimesStep,
    RoadNetworkPrimaryEdgesStep,
    CarAccessEgressStep,
    TripsOpenTripPlannerStep,
    TripsPublicTransitTravelTimeFromR5Step,
    ZonesODFreeFlowTravelTimesStep,
    ZonesODCongestedTravelTimesStep,
    ZonesLevel1RoadNodesStep,
    ZonesLevel2RoadNodesStep,
    ZonesLevel3RoadNodesStep,
    ZonesLevel4RoadNodesStep,
    ZonesLevel5RoadNodesStep,
]
