from __future__ import annotations

import datetime
from pathlib import Path
from typing import TYPE_CHECKING

from loguru import logger

from pymetropolis.metro_common import MetropyError
from pymetropolis.metro_common.utils import pl_duration_to_seconds
from pymetropolis.metro_demand.population.files import (
    TripsDestinationsFile,
    TripsFile,
    TripsOriginsFile,
)
from pymetropolis.metro_demand.routing.files import TripsPublicTransitItinerariesFile
from pymetropolis.metro_pipeline.parameters import (
    DateParameter,
    DurationParameter,
    EnumParameter,
    FloatParameter,
    TimeParameter,
)
from pymetropolis.metro_spatial import OSMStep
from pymetropolis.metro_spatial.gtfs import GTFSStep

if TYPE_CHECKING:
    import geopandas as gpd
    import polars as pl


def run_r5py(
    osm_file: Path,
    gtfs_files: list[Path],
    date: datetime.date,
    trips: pl.DataFrame,
    origins: gpd.GeoDataFrame,
    destinations: gpd.GeoDataFrame,
) -> pl.DataFrame:
    import polars as pl
    import r5py

    logger.debug("Building public-transit network.")
    transport_network = r5py.TransportNetwork(osm_pbf=osm_file, gtfs=gtfs_files)

    logger.debug("Computing public-transit travel-time matrix.")
    results = []
    for (departure_time,), dt_trips in (
        trips.sort("seconds").partition_by("seconds", include_key=False, as_dict=True).items()
    ):
        departure = datetime.datetime.combine(date, datetime.time(0)) + datetime.timedelta(
            seconds=departure_time
        )
        dt_origins = origins.loc[origins["id"].isin(dt_trips["from_id"])]
        dt_destinations = destinations.loc[destinations["id"].isin(dt_trips["to_id"])]
        print(f"Departure: {departure}")
        print(f"Unique origins: {len(dt_origins)}")
        print(f"Unique destinations: {len(dt_destinations)}")
        travel_time_matrix = r5py.TravelTimeMatrix(
            transport_network,
            origins=dt_origins,
            destinations=dt_destinations,
            transport_modes=[r5py.TransportMode.TRANSIT],
            departure=departure,
        )
        dt_df = (
            pl.from_pandas(travel_time_matrix)
            .join(dt_trips, on=["from_id", "to_id"], how="semi")
            .with_columns(seconds=pl.lit(departure_time, dtype=pl.Float64))
        )
        results.append(dt_df)
    df = pl.concat(results, how="vertical_relaxed")
    df = trips.join(df, on=["seconds", "from_id", "to_id"], how="left").select(
        "trip_id", travel_time=pl.duration(minutes="travel_time")
    )
    return df


class TripsPublicTransitTravelTimeFromR5Step(OSMStep, GTFSStep):
    """Computes the trips' travel time by public transit with r5py.

    This is the easiest and (usually) fastest solution to compute public-transit travel times.
    However, it comes with some drawbacks:

    - Time spent in each public-transit modes cannot be weighted (walking vs waiting vs bus vs
      metro...).
    - The itineraries are not computed (needed for some post-simulation analysis).
    - Approximations are made to the origin / destination locations and to the departure time.
    - It is not possible to compute travel time for a given arrival time, only the departure time
      can be controlled.

    If you want a more flexible solution, check out
    [TripsOpenTripPlannerStep](steps.md#tripsopentripplannerstep).

    For this step, `r5py` build the public-transit network from an OpenStreetMap file
    ([`osm_file`](parameters.md#osm_file)) and from GTFS file(s)
    ([`gtfs_files`](parameters.md#gtfs_files)).

    The [`date`](parameters.md#r5date) parameter controls the date used in the public-transit
    timetables, for all queries.
    You need to ensure that the GTFS file(s) have running services at this date.

    The departure time of the trips is control by the [`time_type`](parameters.md#r5time_type) and
    [`time`](parameters.md#r5time) parameters.
    If `time_type` is `"departure"`, then the departure time is given by the trips' ex-ante
    departure times (usually generated by the synthetic population).
    If `time_type` is `"custom"`, then the departure time is given by `time`.

    The running time of r5py does not depend on the number of trips, but rather on the number of
    unique origins, destinations, and departure times.
    When trips' origins and destinations are exact coordinates, as is the case with the Eqasim
    synthetic population, the running time of this step can be very long.
    Therefore, some approximations are done to "group" together similar origins, destinations, and
    departure times.
    You can control these approximations with the
    [`coordinates_rounding`](parameters.md#r5coordinates_routing) and
    [`time_rounding`](parameters.md#r5time_rounding) parameters.
    By default, origins and destinations are rounded to the nearest 500 meters and departure time is
    rounded to periods of 1 hour.

    Example of configuration for this step:

    ```toml
    osm_file = "data/ile-de-france-260101.osm.pbf"
    gtfs_files = ["data/IDFM-gtfs.zip"]

    [r5]
    date = 2026-05-28
    time_type = "departure"
    coord_rounding = 1000
    time_rounding = 1800
    ```
    """

    date = DateParameter(
        "r5.date",
        description="Date to be used for the requests.",
        note="Ensure that the GTFS file read by OpenTripPlanner has active services for this date.",
    )
    time_type = EnumParameter(
        "r5.time_type",
        values=["departure", "custom"],
        description="How the departure time of the requests is defined.",
        note=(
            "If `\"departure\"`, trips' departure times are read from the trips' ex-ante departure "
            "times. "
            'If `"custom"`, the departure times are equal to the value of `r5.time` for all trips. '
        ),
    )
    time = TimeParameter(
        "r5.time",
        description="Departure time of the requests.",
        note=(
            'If `time_type` is `"custom"`, this is the departure time used for all requests. '
            "Otherwise, the value is only used as a default for missing departure times."
        ),
    )
    coord_rounding = FloatParameter(
        "r5.coordinates_rounding",
        default=500.0,
        description="By how many meters trip origin / destination coordinates should be rounded.",
        note=(
            "Smaller values mean that the travel times will be more accurate, but it can result in "
            "a very long running time for the step."
        ),
    )
    time_rounding = DurationParameter(
        "r5.time_rounding",
        default=datetime.timedelta(hours=1),
        description="By how much time trips' departure time should be rounded.",
        note=(
            "Smaller values mean that the travel times will be more accurate, but it can result in "
            "a very long running time for the step."
        ),
    )
    input_files = {
        "trips": TripsFile,
        "origins": TripsOriginsFile,
        "destinations": TripsDestinationsFile,
    }
    output_files = {"costs": TripsPublicTransitItinerariesFile}

    def is_defined(self):
        return self.gtfs_files is not None and self.time_type is not None

    def run(self):
        import geopandas as gpd
        import polars as pl

        trips = self.input["trips"].read()
        if self.time_type == "departure":
            if "departure_time" not in trips.columns:
                trips = trips.with_columns(pl.lit(None, dtype=pl.Duration).alias("departure_time"))
            trips = trips.select("trip_id", seconds=pl_duration_to_seconds("departure_time"))
        else:
            trips = trips.select("trip_id", seconds=pl.lit(None, dtype=pl.Float64))
        if trips["seconds"].is_null().any():
            if self.time is None:
                c = trips["seconds"].null_count()
                raise MetropyError(
                    f"Departure time is undefined for {c:,} trips but the `r5.time` parameter is "
                    "not set."
                )
            if self.time_type == "departure":
                s = trips["seconds"].null_count() / len(trips)
                logger.warning(
                    f"{s:.1%} trips have NULL values for departure time, using default value for "
                    "them"
                )
            # Fill null values for time column with the given time parameter.
            trips = trips.with_columns(pl.col("seconds").fill_null(self.time.seconds()))

        # Read origin / destination coordinates.
        origins = self.input["origins"].read()
        origins_df = pl.DataFrame(
            {
                "trip_id": origins["trip_id"],
                "origin_x": origins.geometry.x,
                "origin_y": origins.geometry.y,
            }
        )
        trips = trips.join(origins_df, on="trip_id")
        destinations = self.input["destinations"].read()
        destinations_df = pl.DataFrame(
            {
                "trip_id": destinations["trip_id"],
                "destination_x": destinations.geometry.x,
                "destination_y": destinations.geometry.y,
            }
        )
        trips = trips.join(destinations_df, on="trip_id")

        # Round origin / destination coordinates and departure time.
        c_round = self.coord_rounding
        t_round = self.time_rounding.total_seconds()
        trips = trips.with_columns(
            origin_x=pl.col("origin_x").truediv(c_round).round().mul(c_round),
            origin_y=pl.col("origin_y").truediv(c_round).round().mul(c_round),
            destination_x=pl.col("destination_x").truediv(c_round).round().mul(c_round),
            destination_y=pl.col("destination_y").truediv(c_round).round().mul(c_round),
            seconds=pl.col("seconds").truediv(t_round).round().mul(t_round),
        )
        unique_origins = (
            trips.select("origin_x", "origin_y")
            .unique()
            .with_columns(from_id=pl.int_range(pl.len()))
        )
        trips = trips.join(unique_origins, on=["origin_x", "origin_y"])
        unique_destinations = (
            trips.select("destination_x", "destination_y")
            .unique()
            .with_columns(to_id=pl.int_range(pl.len()))
        )
        trips = trips.join(unique_destinations, on=["destination_x", "destination_y"])
        origins_gdf = gpd.GeoDataFrame(
            data={"id": unique_origins["from_id"]},
            geometry=gpd.GeoSeries.from_xy(
                unique_origins["origin_x"], unique_origins["origin_y"], crs=origins.crs
            ),
        )
        destinations_gdf = gpd.GeoDataFrame(
            data={"id": unique_destinations["to_id"]},
            geometry=gpd.GeoSeries.from_xy(
                unique_destinations["destination_x"],
                unique_destinations["destination_y"],
                crs=destinations.crs,
            ),
        )
        trips = trips.select("trip_id", "from_id", "to_id", "seconds")

        df = run_r5py(
            self.osm_file, self.gtfs_files, self.date, trips, origins_gdf, destinations_gdf
        )
        self.output["costs"].write(df)
